name: settlr
services:
  # Settlr Application
  settlr:
    container_name: settlr
    image: chavda2772/settlr:latest
    ports:
      - '6854:3000'
    restart: unless-stopped
    labels:
      icon: https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr/icon_with_bg.png
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_NAME=Settlr
      - NEXT_PUBLIC_APP_DESCRIPTION="Settlr for managing personal finance"

      # Database
      - DATABASE_URL=postgresql://settlr:settlrpassword@db:5432/settlr

      # Better Auth
      - BETTER_AUTH_URL=http://localhost:6854
      - BETTER_AUTH_SECRET=faTlJkmKxeBUe6sNdiJ4QaNA6elg1elw
      - BETTER_AUTH_TRUSTED_ORIGINS=http://example.com,http://*.example.com

      # Optional integrations
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - DISCORD_CLIENT_ID=
      - DISCORD_CLIENT_SECRET=

      # Email (optional)
      - FROM_EMAIL=<settlr@example.com>
      - SMTP_HOST=mail.example.com
      - SMTP_PASS=<password>
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER=settlr@example.com

    volumes:
      - /DATA/AppData/$AppID/web:/app/data
    networks:
      - settlr-net
    command: /bin/sh -c "npm run db:deploy && npm start"

networks:
  settlr-net:
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  author: Chavda Mahesh
  category: Finance
  title:
    en_us: Settlr With DB
  description:
    en_us: |
      Settlr is a self-hosted financial tracking application.

      Features:
      - Track income & expenses
      - Manage parties and transactions
      - Business-level accounting
      - Secure authentication
      - Clean and responsive UI
  developer: Chavda Mahesh
  icon: https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr_with_DB/icon_with_bg.png
  main: settlr
  port_map: '6854'
  project_url: https://github.com/Murlidhar08/settlr
  screenshot_link:
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr_with_DB/screenshot-1.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr_with_DB/screenshot-2.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr_with_DB/screenshot-3.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr_with_DB/screenshot-4.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr_with_DB/screenshot-5.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr_with_DB/screenshot-6.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr_with_DB/screenshot-7.png
  store_app_id: settlr-with-db
  tagline:
    en_us: Simple business accounting and transaction management system.
  thumbnail: https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr_with_DB/icon.png
  tips:
    before_install:
      en_us: |
        Default login will require configuration.

        Access the app at:
        http://<your-server-ip>:6854

        Make sure to update:
        - DATABASE_URL (pre-configured for internal DB)
        - BETTER_AUTH_SECRET
        - OAuth credentials (optional)
