name: settlr
services:
  # Settlr Application
  settlr:
    container_name: settlr
    image: chavda2772/settlr:latest
    ports:
      - '6854:3000'
    restart: unless-stopped
    labels:
      icon: https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr/icon_with_bg.png
    environment:
      # Application
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_NAME=Settlr
      - NEXT_PUBLIC_APP_DESCRIPTION="Settlr for managing personal finance"

      # Database
      - DATABASE_URL=

      # Better Auth
      - BETTER_AUTH_URL=https://settlr.example.com
      - BETTER_AUTH_SECRET=lMD1eol2MrTxIZixGYyjwT0G0DQJ6oLJ
      - BETTER_AUTH_TRUSTED_ORIGINS=https://settlr-domain.example.com,https://*.example.com

      # Optional integrations
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - DISCORD_CLIENT_ID=
      - DISCORD_CLIENT_SECRET=

      # Email (optional)
      - FROM_EMAIL="Settlr <settlr@example.com>"
      - SMTP_HOST="mail.example.com"
      - SMTP_PASS=PASSWORD
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER="settlr@example.com"

    volumes:
      - /DATA/AppData/$AppID/web:/app/data
    networks:
      - settlr-network
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:3000/health']
    depends_on:
      settlr-migrate:
        condition: service_completed_successfully

  prisma-studio:
    image: node:24.15.0
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - /DATA/AppData/$AppID/studio:/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - '5555:5555'
    environment:
      - DATABASE_URL="postgresql://postgres:postgres@example.com:5432/settlr_v2"
    networks:
      - settlr-network

  settlr-migrate:
    image: node:24.15.0
    container_name: settlr-migrate
    working_dir: /app
    volumes:
      - /DATA/AppData/$AppID/migration:/app
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@example.com:5432/settlr_v2'
    networks:
      - prisma-network
    command: ['npx', 'prisma', 'migrate', 'deploy']
    restart: 'no'

networks:
  settlr-network:
    name: settlr-network

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  author: Chavda Mahesh
  category: Finance
  title:
    en_us: Settlr
  description:
    en_us: |
      Settlr is a self-hosted financial tracking application.

      Features:
      - Track income & expenses
      - Manage parties and transactions
      - Business-level accounting
      - Secure authentication
      - Clean and responsive UI
  developer: Chavda Mahesh
  icon: https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr/icon_with_bg.png
  main: settlr
  port_map: '6854'
  project_url: https://github.com/Murlidhar08/settlr
  screenshot_link:
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr/screenshot-1.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr/screenshot-2.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr/screenshot-3.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr/screenshot-4.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr/screenshot-5.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr/screenshot-6.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/Settlr/screenshot-7.png
  store_app_id: settlr
  tagline:
    en_us: Simple business accounting and transaction management system.
  thumbnail: https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/settlr/icon.png
  tips:
    before_install:
      en_us: |
        Default login will require configuration.

        Access the app at:
        http://<your-server-ip>:6854

        Make sure to update:
        - DATABASE_URL
        - BETTER_AUTH_SECRET
        - OAuth credentials (optional)
