# https://github.com/IceWhaleTech/CasaOS-AppStore/blob/main/CONTRIBUTING.md

name: settlr
services:
  settlr:
    container_name: settlr
    image: chavda2772/settlr:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/Murlidhar08/settlr@develop/resources/light_logo.png
    network_mode: bridge
    ports:
      - target: 3000
        published: "6854"
        protocol: tcp
    restart: unless-stopped
    environment:
      - BETTER_AUTH_SECRET=CBRi63R1uFOM7kBZVTwZ1H1rNkpfH4S5
      - BETTER_AUTH_URL=<APPLICATION URL>
      - DATABASE_URL=<DATABASE URL>
      - DISCORD_CLIENT_ID=
      - DISCORD_CLIENT_SECRET=
      - FROM_EMAIL=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - NEXT_PUBLIC_APP_NAME=Settlr
      - NODE_ENV=production
      - SMTP_HOST=
      - SMTP_PASS=
      - SMTP_PORT=
      - SMTP_SECURE=true
      - SMTP_USER=
    healthcheck:
      test: curl --fail -s http://localhost:3000/health || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
    x-casaos:
      ports:
        - container: "6854"
          description:
            en_us: ""
x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  author: chavda mahesh
  category: Financial App
  description:
    en_us: |
      This is the settlr application

      🚨 Note: Check this note.
  developer: Chavda Mahesh
  icon: https://cdn.jsdelivr.net/gh/Murlidhar08/settlr@develop/resources/light_logo.png
  index: /
  main: settlr
  port_map: "6854"
  project_url: https://github.com/mr-manuel/CasaOS-HomeAutomation-AppStore
  screenshot_link:
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/settlr/screenshot-1.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/settlr/screenshot-2.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/settlr/screenshot-3.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/settlr/screenshot-4.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/settlr/screenshot-5.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/settlr/screenshot-6.png
  store_app_id: settlr
  tagline:
    en_us: Manage all types of time series data in a single, purpose-built database.
  thumbnail: https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/settlr/icon.png
  tips:
    before_install:
      en_us: |
        The database will be reachable at port `6854`.

        [Website](https://www.influxdata.com/settlr/) &bull; [Documentation](https://docs.influxdata.com/settlr/)
  title:
    en_us: Settlr
