name: property-hub-with-db
services:
  # Property_Hub Application
  property-hub:
    container_name: property-hub-web
    image: chavda2772/property-hub:latest
    ports:
      - '6655:3000'
    restart: unless-stopped
    labels:
      icon: https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/property-hub/icon_with_bg.png
    environment:
      # Application
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_NAME="Property Hub"
      - NEXT_PUBLIC_APP_DESCRIPTION="Property Hub is your all-in-one platform to manage real estate listings, clients, and agents effortlessly."

      # Database
      - DATABASE_URL="postgresql://property_admin:Admin123@postgres_db:5432/property_hub?schema=public"

      # Better Auth
      - BETTER_AUTH_URL="https://hub.example.com"
      - BETTER_AUTH_SECRET="lMD1eol2MrTxIZixGYyjwT0G0DQJ6oLJ"
      - BETTER_AUTH_TRUSTED_ORIGINS="https://*.example.com"

      # Optional integrations
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - DISCORD_CLIENT_ID=
      - DISCORD_CLIENT_SECRET=

      # Email (optional)
      - FROM_EMAIL="Property_Hub <property-hub@example.com>"
      - SMTP_HOST="mail.example.com"
      - SMTP_PASS=PASSWORD
      - SMTP_PORT=587
      - SMTP_SECURE=false
      - SMTP_USER="property-hub@example.com"

    volumes:
      - /DATA/AppData/$AppID/uploads:/uploads
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'http://localhost:3000/health' ]
    depends_on:
      property_db:
        condition: service_healthy
    networks:
      - prisma-network

  # Postgress database service
  property_db:
    container_name: property_db
    environment:
      - POSTGRES_DB=property_hub
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_USER=property_admin
    hostname: property_db
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U property_admin -d property_hub
      timeout: 2s
      interval: 5s
      retries: 20
    image: postgres:17.4
    labels:
      icon: https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/property-hub/icon_with_bg.png
    restart: always
    volumes:
      - /DATA/AppData/$AppID/db:/var/lib/postgresql/data
    networks:
      - prisma-network
    privileged: false

  # Prisma Studio service for database access
  prisma-studio:
    image: node:24-alpine
    container_name: prisma-studio
    environment:
      - DATABASE_URL="postgresql://property_admin:Admin123@property_db:5432/property_hub?schema=public"
    ports:
      - '5555:5555'
    command:
      - npx prisma studio --port 5555 --browser none
    restart: unless-stopped
    working_dir: /app
    networks:
      - prisma-network
    depends_on:
      property_db:
        condition: service_healthy

networks:
  prisma-network:
    name: prisma-network

x-casaos:
  architectures:
    - amd64
    - arm64
    - arm
  author: Chavda Mahesh
  category: Real Estate
  title:
    en_us: Property Hub
  description:
    en_us: |
      Property Hub is your all-in-one platform to manage real estate listings, clients, and agents effortlessly.

      Features:
      - Manage real estate listings & properties
      - Track clients, inquiries, and agent assignments
      - Interactive dashboard and property analytics
      - Secure user authentication
      - Clean, modern, and responsive user interface
  developer: Chavda Mahesh
  icon: https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/property-hub/icon_with_bg.png
  main: property-hub
  port_map: '6655'
  project_url: https://github.com/Murlidhar08/property-hub
  screenshot_link:
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/property-hub/screenshot-1.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/property-hub/screenshot-2.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/property-hub/screenshot-3.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/property-hub/screenshot-4.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/property-hub/screenshot-5.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/property-hub/screenshot-6.png
    - https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/property-hub/screenshot-7.png
  store_app_id: property-hub
  tagline:
    en_us: Manage your real estate listings, clients, and agents effortlessly.
  thumbnail: https://raw.githubusercontent.com/Murlidhar08/CasaOs-AppStore/refs/heads/main/Apps/property-hub/icon.png
  tips:
    before_install:
      en_us: |
        Default login will require configuration.

        Access the app at:
        http://<your-server-ip>:6655

        Make sure to update:
        - DATABASE_URL
        - BETTER_AUTH_SECRET
        - OAuth credentials (optional)
